name = input("Whats your name?: ")
print((f"{name} lets reflect on your phase one journey"))
print("*"*60)
print("Phase 1 achievements")
print("*"*60)
print("Week1: Hello World and Python basics")
print("Week2: Variables and calculator")
print("Week3: Conditions and number guessing game")
print("Week4: Loops and game completion")
print("Week5: Functions and rock paper scissors game")
print("Week6: Random numbers and LIst")
print("Week7: Debugging practice")
print("Week8: ascii art")
print("Week9: List and arrays deeper")
print("Week10: Loops and list practice")
print("Week11: Strings and formatting")
print("Week12: Braching storylines")
print("Week13: Review and mini challenges")
print("*"*60)
print("Skills mastered")
print("*"*60)
print("Variables and data types")
print("Input and output")
print("Conditional logic if/elif/else")
print("Loops for/while")
print("Functions and code organisation")
print("List and data structures")
print("String manipulation")
print("Random number generation")
print("Error handling and debugging")
print("*"*60)
print("Projects completed")
print("*"*60)
print("Calculator")
print("Number guessing game")
print("Rock paper scissors game")
print("Playlist generator")
print("Adventure game")
print("FizzBuzz challenge")
print("Advanced calculator")
print("*"*60)
print("Ready for phase 2")
print("*"*60)
print("File handling and data saving")
print("Loading data")
print("Working with files")
print("Building projects that remembers data")
print((f"{name} youve built an amazing foundations in programming, your ready to take on new challenges."))
print("CONGRATULATIONS ON COMPLETEING PHASE 1")



